#include "arduino_secrets.h"
#include <DHT.h>
#include <DHT_U.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/8b4309bf-7eb0-41f4-98cc-148fed0f8394 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight light;
  CloudTemperatureSensor temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define DHTPIN 15 //Digital pin connected to DHT sensor
#define DHTTYPE DHT11 //DHT11
DHT dht(DHTPIN,DHTTYPE);

unsigned long previousMillis=0; //Stores last time data was sent
const long interval = 5000;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(2,OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  unsigned long currentMillis = millis();

  if(currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    sendDHT11Data();
  }
  
}



/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  digitalWrite(2,light);
  // Add your code here to act upon Light change
}

void sendDHT11Data() {

  temperature = dht.readTemperature();

  if(isnan(temperature)) {
Serial.println("Failed to read DHT sensor!");
  return;
}

  Serial.print("Temperature: ");
  Serial.print(temperature);
  Serial.print("°C");
}

  
